Create form that shows all customers and their calls (use JQgrid jquery plugin)
<?php
//add js on the bottom on the page

    $this->InlineScript()->appendFile($this->basePath() .'/js/alex/plugin/grid.locale-en.js');
//    $this->InlineScript()->appendFile($this->basePath() .'/js/alex/plugin/jquery.jqGrid.min.js');
    $this->InlineScript()->appendFile($this->basePath() .'/js/alex/plugin/jquery.jqGrid.js');
    $this->InlineScript()->appendFile($this->basePath() .'/js/alex/APP.js');
    $this->InlineScript()->appendFile($this->basePath() .'/js/alex/customers_and_calls.js');

// add css on the top of the page
    $this->headLink()->appendStylesheet($this->basePath() .'/css/lib/jquery-ui-1.10.3.custom.css');
    $this->headLink()->appendStylesheet($this->basePath() .'/css/lib/ui.jqgrid.css');


?>

<script>
    var dataGrid = <?php echo $this->callsAndCustomersJson;?>;
</script>
<div>
<table id="list2"></table>
<div id="pager2"></div>
</div>
